cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
import:
  - '@kurone-kito/cspell-config'
version: '0.2'
words:
  - aicommits
  - GHEC
  - GHES
  - idd
  - Kiro
  - kurone
  - minimizable
  - ministral
  - nvmrc
  - rollup
  - tsfile
  - unmigrated
  - unmirrored
  - unrouted
  - unrs
  - WHATWG
