compressionLevel: mixed

enableGlobalCache: false

npmPublishAccess: public

npmScopes:
  kurone-kito:
    npmAuthToken: "${NPM_TOKEN:-invalid_token}"
    npmRegistryServer: "https://registry.npmjs.com"

packageExtensions:
  "@commitlint/cli@*":
    peerDependencies:
      typescript: ">=4.9.5"
  "@commitlint/load@*":
    dependencies:
      "@types/node": "*"
    peerDependencies:
      typescript: ">=4.9.5"
  "@eslint/compat@*":
    peerDependencies:
      "@types/eslint": "*"
  "@eslint/markdown@*":
    peerDependencies:
      mdast: "*"
  "@typescript-eslint/type-utils@*":
    peerDependencies:
      eslint: ^8.57.0 || ^9.0.0
  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: ">=4.2.0"
  eslint-plugin-storybook@*:
    peerDependencies:
      typescript: ">=4.2.0"
  typescript-eslint@*:
    peerDependencies:
      eslint: ^8.57.0 || ^9.0.0

pnpEnableEsmLoader: true
