compressionLevel: mixed

enableGlobalCache: false

npmPublishAccess: public

npmScopes:
  kurone-kito:
    npmAuthToken: "${NPM_TOKEN:-invalid_token}"
    npmRegistryServer: "https://registry.npmjs.com"

pnpEnableEsmLoader: true
