configDependencies:
  '@pnpm/plugin-types-fixer': 0.1.0+sha512-bLww63gRHi7siYTqFJb5qNdcXadU0jv20Et6z5AryMZ7FlLolbEJOrXLpg8+amQZNHHNW1dfFUBGVw/9ezQbFg==
enableGlobalVirtualStore: true
engineStrict: true
gitChecks: false
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: true
packages:
  - packages/*
pmOnFail: warn
shellEmulator: true

# Prevent parallel execution of publish. Since no `--workspace-concurrency`
# option exists for pnpm publish, we're increasing the number from 1 as
# necessary.
workspaceConcurrency: 1
