allowCompoundWords: true
dictionaries:
  - bash
  - companies
  - cpp
  - csharp
  - css
  - docker
  - dotnet
  - en_US
  - en-gb
  - filetypes
  - fonts
  - fsharp
  - fullstack
  - git
  - html
  - lorem-ipsum
  - node
  - npm
  - powershell
  - php
  - sql
  - softwareTerms
  - terraform
  - typescript
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
id: kurone-kito
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - .yarn
  - cspell.config.yml
  - node_modules
  - pnpm-lock.yaml
  - yarn.lock
ignoreRegExpList:
  # Ignore the scope name of the packages.
  - '@[a-zA-Z0-9_-]+/'
language: en
useGitignore: true
version: '0.2'
words:
  - dedup
  - deprioritize
  - desync
  - desynced
  - dprint
  - esync
  - hoge
  - isort
  - kito
  - kuron
  - kuroné
  - lintstagedrc
  - noconflict
  - npmjs
  - onnx
  - oxlint
  - piyo
  - pylint
  - pyproject
  - pytest
  - qwen
  - solidjs
  - toctou
  - undispositioned
  - unioned
  - unpushed
  - unreplied
  - unscored
  - unwaived
  - waivable
