allowCompoundWords: true
dictionaries:
  - bash
  - companies
  - cpp
  - csharp
  - docker
  - dotnet
  - en_US
  - en-gb
  - eo
  - filetypes
  - fonts
  - fullstack
  - git
  - html
  - lorem-ipsum
  - markdown
  - misc
  - node
  - npm
  - powershell
  - shell
  - softwareTerms
  - typescript
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
id: kurone-kito
language: en,ja
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - .yarn
  - cspell.config.yml
  - node_modules
  - yarn.lock
ignoreRegExpList:
  # Ignore the scope name of the packages.
  - '@[a-zA-Z0-9_-]+/'
words:
  - aicommits
  - fuga
  - hoge
  - kito
  - Kuroné
  - lintstagedrc
  - piyo
  - noconflict
useGitignore: true
version: '0.2'
