endOfLine: lf
overrides:
  - files:
      - .yarnrc.yml
      - yarn.lock
    options:
      singleQuote: false
plugins:
  - prettier-plugin-packagejson
  - prettier-plugin-sh
  - prettier-plugin-sort-json
singleQuote: true
