endOfLine: lf
overrides:
  - files:
      - .yarnrc.yml
      - yarn.lock
    options:
      singleQuote: false
  - files:
      - '*.json'
      - '*.jsonc'
    options:
      trailingComma: none
singleQuote: true
