#!/bin/sh
# -*- mode: sh -*-
# vim: set ft=sh :

if [ ! -e packages/biome-config/biome.json ]; then
  corepack enable
  corepack install
  pnpm install --prefer-frozen-lockfile --prefer-offline
  pnpm run build
fi

pnpm exec lint-staged -r
