concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
name: The CI workflow on push as a feature branch
on:
  push:
    branches:
      - '**'
      - '!main'
permissions:
  contents: read
run-name: Pushed the feature branch by @${{ github.actor }}
jobs:
  build:
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    env:
      PNPM_CONFIG_ENABLE_GLOBAL_VIRTUAL_STORE: 'false'
    name: The build process
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Stages the pushed branch
        uses: actions/checkout@v7
      - name: Setup the pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false
      - name: Prepare the Node.js version ${{ matrix.node-version }} environment
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          check-latest: true
          node-version: ${{ matrix.node-version }}
      - env:
          HUSKY: 0
        name: Install the dependencies and build the project
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Check the code style and run the test suite
        run: pnpm run test
    strategy:
      matrix:
        node-version:
          - 22.x
          - 24.x
          - 26.x
        platform:
          - os: ubuntu-latest
            shell: bash
          - os: windows-latest
            shell: bash
          - os: windows-latest
            shell: powershell
      fail-fast: false
    timeout-minutes: 5
