name: Publish the packages
run-name: Publish by @${{ github.actor }}
on:
  release:
    types:
      - published
jobs:
  build:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/common-release.yml
    with:
      next: ${{ github.event.release.prerelease }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
